services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - ./DB/CreateScript.sql:/docker-entrypoint-initdb.d/init.sql
      - chatco-db:/var/lib/postgresql/data

volumes:
  chatco-db:
