vaadin.launch-browser=true
spring.application.name=chat-co

# LDAPS Konfiguration
spring.ldap.urls=ldaps://ldap.chat-co.net:636
spring.ldap.base=dc=chatco,dc=net
spring.ldap.username=cn=admin,dc=chatco,dc=net
spring.ldap.password=${ldap.password}

spring.ldap.embedded.validation.enabled=false
# Truststore Setup (referenziert das Passwort aus secret.properties)
#server.ssl.trust-store=truststore.jks
#server.ssl.trust-store-password=${truststore.password}
server.port=8080
System.setProperty("javax.net.ssl.trustStore", "truststore.jks");