spring.config.import=optional:classpath:secret.properties
vaadin.launch-browser=true
spring.application.name=chat-co
server.forward-headers-strategy=framework

# LDAPS Konfiguration
spring.ldap.urls=ldaps://ldap.chat-co.net:636
spring.ldap.base=dc=chatco,dc=net
spring.ldap.username=uid=fd-admin,ou=people,dc=chatco,dc=net
spring.ldap.password=${ldap.password}

spring.ldap.embedded.validation.enabled=false

server.port=8080
System.setProperty("javax.net.ssl.trustStore", "truststore.jks");

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db.chat-co.net:5432/appdb
spring.datasource.username=appuser

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC